server:
  port: 4000
  host: localhost
db:
  host: localhost
  port: 5432
  user: username
  password: password
  dbName: db
rabbitmq:
  host: localhost
  port: 5672
  user: username
  password: password
jobs:
  exchange: jobs-local
jobEventsConsumer:
  consumer: job-events-local-consumer
  queue: job-events-local
  exchange: job-events-local
